User single_underscore_or single *asterisks* to get italics

In [1]:
#convention for importing numpy

In [2]:
import numpy as np

In [3]:
arr = [6, 7, 8, 9]
print(type(arr)) # <class 'list'>

<class 'list'>


In [4]:
a = np.array(arr)
print(type(a)) # print <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(4,)


In [6]:
print(a.dtype)

int32


get the dimentsion of a with ndim

In [7]:
import numpy as np

In [8]:
print(a.ndim) #print 1

1


In [9]:
b =np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
print(b.ndim) # print 2

2


In [12]:
b.shape # print (2,3) - b a 2d array with 2 rows and 3 columns

(2, 3)

In [13]:
# a 2x3 array with random value

In [14]:
np.random.random((2, 3))
                      

array([[0.67130843, 0.46803375, 0.52335935],
       [0.8384319 , 0.20023598, 0.66534227]])

In [15]:
np.zeros((2, 3)) #arrays of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2, 3)) #arrays of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.identity (3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Intra-operability of arrays and scalars.

In [18]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

In [19]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [20]:
c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [21]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [22]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

Indexing with arrays & Using arrays for data processing

In [23]:
##The elements in the example arrays above can be accessed by indexing like lists in Python such that:

In [24]:
a[0]

6

In [25]:
a[3]

9

In [26]:
b[0,0]

1

In [27]:
b[1,2]

6

In [28]:
c[0,1]

8.0

In [29]:
##Elements in arrays  can also be retrieved by slicing rows and columns or a combination of indexing and slicing.

In [30]:
d[1,  0:2]

array([9., 8.])

In [31]:
e = np.array([[10, 11, 12],[13, 14, 15], 
              [16, 17, 18],[19, 20, 21]])

In [32]:
# slicing

In [33]:
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [34]:
#There are other advanced methods of indexing which are shown below.
# integer indexing

In [35]:
e[[2, 0, 3, 1],[2, 1, 0, 2]]

array([18, 11, 19, 15])

In [36]:
# boolean indexing meeting a specified condition

In [37]:
e[e>15]

array([16, 17, 18, 19, 20, 21])